### ISSUE TITLE
import caused issues

### ISSUE THREAD

**Issue by ollyboy** [sunel/Magento-Import-Export#2]
Hi, import caused the product edit functions to crash with white screen. attributes and sets looked ok and could be edited but errors generated. The php error on screen was something to do with null/empty attribute. Could you add some DB integrity checking?? or is there a tool to do this??

2015-08-12T00:03:00+00:00 ERR (3): Warning: array_combine() expects parameter 2 to be array, boolean given  in /var/www/magento/shell/import.php on line 226
2015-08-12T00:03:00+00:00 ERR (3): Notice: Undefined offset: 1  in /var/www/magento/shell/import.php on line 337
2015-08-12T00:03:00+00:00 ERR (3): Notice: Undefined offset: 1  in /var/www/magento/shell/import.php on line 342
2015-08-12T00:03:00+00:00 ERR (3): Notice: Undefined offset: 1  in /var/www/magento/shell/import.php on line 337
2015-08-12T00:03:00+00:00 ERR (3): Notice: Undefined offset: 1  in /var/www/magento/shell/import.php on line 342
2015-08-12T00:03:00+00:00 ERR (3): Notice: Undefined offset: 1  in /var/www/magento/shell/import.php on line 337
2015-08-12T00:03:00+00:00 ERR (3): Notice: Undefined offset: 1  in /var/www/magento/shell/import.php on line 342

**Comment by ollyboy** [comment]
I who why. The attribute dump dumps out the core product attributes like name, description, sku. When these are loaded back in they stuff up the DB structure. Edit your attributes file and make sure it has no core attributes.

**Comment by sunel** [comment]
core attributes will not get effected in the process it will be skipped check this [code](https://github.com/sunel/Magento-Import-Export/blob/master/import.php#L377) block 
Magento will throw exception if we try to update the core attributes

**Comment by ollyboy** [comment]
Manybe core is not the right word. All I can say is that if you import a file that has standard attributes of the product it will crash the product edit functions. ie attributes like sku, product_description

**Comment by sunel** [comment]
Are you using magento default import (through admin panel)

**Comment by ollyboy** [comment]
Hi, no was using your import. Your export definitely dumps out all the
product attributes and the import breaks the site unless these are removed.
It will be ok for single site dump and load but I am doing migration form
1.7.2 to 1.9.2. If you have code to try to exclude product/core attributes
then its not working.

Also your export does not include the SKU id for additional images so MAGMI
cant reload these. Not a hugh issue can work around that but could be
better.

Thanks for your work, just trying to help the next guy not break his site:)

On Wed, Aug 12, 2015 at 6:53 PM, Sunel notifications@github.com wrote:

> Are you using magento default import (through admin)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sunel/Magento-Import-Export/issues/2#issuecomment-130221275
> .

## 

Regards

Steve McDonald
xpractical.com.au
0411263400

Check out my holiday rental
http://www.stayz.com.au/accommodation/vic/phillip-island-gippsland/inverloch/84154

**Comment by sunel** [comment]
So basically what you say is , when you have default attributes in the sheet which you have exported and try to import, it throws error.

If yes can you please post the full error stack. 

and  for the additional media images check [this](https://github.com/sunel/Magento-Import-Export/blob/master/export_product.php#L1010) i already has it

**Comment by ollyboy** [comment]
Yes thats it. Will see if I can regen the fault. Not sure what you are
showing in the media link

On Wed, Aug 12, 2015 at 8:39 PM, Sunel notifications@github.com wrote:

> So basically what you say is , when you have default attributes in the
> sheet which you have exported and try to import, it throws error.
> 
> If yes can you please post the full error stack.
> 
> ad for the additional media images check this
> https://github.com/sunel/Magento-Import-Export/blob/master/export_product.php#L1010
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sunel/Magento-Import-Export/issues/2#issuecomment-130252668
> .

## 

Regards

Steve McDonald
xpractical.com.au
0411263400

Check out my holiday rental
http://www.stayz.com.au/accommodation/vic/phillip-island-gippsland/inverloch/84154
