### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by uldemarche** [sunel/Magento-Import-Export#4]
When submitting the command by shell "php import.php" , I always get the message
"Fatal error: Out of memory (allocated 1721499648)"
Happens on both the remote server and the local server

On xampp I put in import.php: 
" Ini_set ('memory_limit', '14400M'); "

But always goes wrong

**Comment by sunel** [comment]
" Ini_set ('memory_limit', '-1'); " try this

**Comment by sunel** [comment]
What is the count of Attribute ?

**Comment by sunel** [comment]
closing the issue
