### ISSUE TITLE
Groups in Default Attribute set gone missing

### ISSUE THREAD

**Issue by bmshubham** [sunel/Magento-Import-Export#5]
Hi There,
Thanks for making this fantastic script to export and import attributes and products for magento.
I've used this script to export attributes and is done successfully. 
But, when I'm importing all gone well in terminal and ends up with a successful message. but I'm getting a blank Default Attribute set in backend, even default mandatory one are not showing. Attributes are available in DB because when I'm creating one with same name it says already exist. Also, all the default attributes are available in product page left menu.
Check below screenshots.
![attribute_set](https://user-images.githubusercontent.com/26863767/39228596-8febf2a6-487c-11e8-9f2c-c03b926ade7b.png)
![attribute_set_2](https://user-images.githubusercontent.com/26863767/39228764-5f9d46a8-487d-11e8-86ad-1b1b0a367a81.png)
![default_set](https://user-images.githubusercontent.com/26863767/39228788-785f2dd2-487d-11e8-87ed-6c4cc46e3ef8.png)
![product_page](https://user-images.githubusercontent.com/26863767/39228828-9af5ab5a-487d-11e8-940c-12c8f9606dc6.png)

**Comment by sunel** [comment]
Can you confirm if the values are added to the  tables like eav_attribute 

Can you mention the magento version that was used to export and import.

**Comment by bmshubham** [comment]
My current magento version is 1.9.3.8.
Yes, I got new attribute entries in **eav_attribute** table and also respected option values in **eav_attribute_option_value** table.
One more thing I do not get option values for existing attribute added/updated.

**Comment by sunel** [comment]
@shashank-abacus 

I have Fixed the issue and made some improvements to the script, remove the old code and try the new one form the repo.

Please read the README file
